# Generated by Django 5.2.12 on 2026-05-29 09:17

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384),
        ),
        migrations.AlterField(
            model_name='resumeembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384),
        ),
    ]
